services:
  - type: web
    name: fruit-classifier
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 4 --threads 2 --timeout 300 --graceful-timeout 300 --preload --log-level warning --access-logfile -
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
